
tasks:
  # - init: echo 'init script' # runs during prebuild
  - command: sudo apt-get install -y ruby-full build-essential zlib1g-dev
  - command: echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc && echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc && echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc && source ~/.bashrc
  - command: gem install jekyll bundler

# # List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
vscode:
  extensions:
    - ritwickdey.liveserver
    - foxundermoon.shell-format
    - tabnine.tabnine-vscode
    - timdmackey.mechanic-liquid
    - vscode.javascript
    - vscode.html
