image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ritwickdey.liveserver
    - foxundermoon.shell-format
    - tabnine.tabnine-vscode
    - timdmackey.mechanic-liquid
    - vscode.javascript
    - vscode.html
